services:

  hz:
    image: hazelcast/hazelcast:5.2.1
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
      CLASSPATH: /project/common/target/common-1.0-SNAPSHOT.jar
    volumes:
      - ".:/project"
    networks:
      - hznet

  mc:
    image: hazelcast/management-center:5.2.1
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hz:5701
    ports:
      - "8080:8080"
    networks:
      - hznet

  submit_aggregation_job:
    image: hazelcast/hazelcast-enterprise:5.2.1
    volumes:
      - ".:/project"
    command: >
      hz-cli submit 
          -v 
          -c=hazelcast.platform.labs.machineshop.AggregationPipeline 
          -t=dev@hz   
          -n=aggregator 
          /project/pipelines/target/pipelines-1.0-SNAPSHOT.jar
    networks:
    - hznet

  submit_summary_service_job:
    image: hazelcast/hazelcast-enterprise:5.2.1
    volumes:
      - ".:/project"
    command: >
      hz-cli submit 
          -v 
          -c=hazelcast.platform.labs.machineshop.MachineStatusServicePipeline 
          -t=dev@hz   
          -n=status_service
          /project/pipelines/target/pipelines-1.0-SNAPSHOT.jar 
          machinestatus_request 
          machinestatus_response
    networks:
      - hznet

  refdata_loader:
    image: openjdk:11
    command: java -jar /project/refdata-loader/target/refdata-loader-1.0-SNAPSHOT.jar
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev
      MACHINE_COUNT: 10
      SIMULATOR_CONFIG_FILE: /project/config/machine_profiles_small.csv
    volumes:
      - ".:/project"
    networks:
      - hznet

  event_generator:
    image: openjdk:11
    command: java -jar /project/event-generator/target/event-generator-1.0-SNAPSHOT.jar
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev 
      MACHINE_COUNT: 10
    volumes:
      - ".:/project"
    networks:
      - hznet
  
  ui:
    build:
      context: ./ui
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev
    ports:
      - "8050:8050"
    networks:
      - hznet

  status_service:
    image: openjdk:11
    command: >
      java -Dhazelcast.client.config=/project/config/hazelcast-client.yaml 
        -jar /project/machine-status-service/target/machine-status-service-1.0-SNAPSHOT.jar
    environment:
      HZCLIENT_INSTANCENAME: status_service
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev
      hazelcast.pipeline.dispatcher.embed_hazelcast: false
      hazelcast.pipeline.dispatcher.request_timeout_ms: 2000
    volumes:
      - ".:/project"
    ports:
      - "8888:8080"
    networks:
      - hznet

networks:
  hznet: 
  