services:

  hz:
    image: hazelcast/hazelcast:5.2.1
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
      CLASSPATH: /project/common/target/common-1.0-SNAPSHOT.jar
    volumes:
      - ".:/project"
    networks:
      - hznet
    profiles:
      - disabled

  mc:
    image: hazelcast/management-center:5.2.1
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hz:5701
    ports:
      - "8080:8080"
    networks:
      - hznet
    profiles:
      - disabled

  cli:
    image: hazelcast/hazelcast:5.2.1
    command: hz-cli
    volumes:
      - ".:/project"
    command: >
      tail -f < /dev/null
    networks:
    - hznet
    profiles:
      - disabled

  refdata_loader:
    image: openjdk:11
    command: java -jar /project/refdata-loader/target/refdata-loader-1.0-SNAPSHOT.jar
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev
      MACHINE_COUNT: 2000
      SIMULATOR_CONFIG_FILE: /project/config/machine_profiles_small.csv
      VIRIDIAN_SECRETS_DIR: /project/hzcloud_c8930fck_keys
      VIRIDIAN_CLUSTER_ID: pr-c8930fck
      VIRIDIAN_PASSWORD: d2d46ffa1a2
      VIRIDIAN_DISCOVERY_TOKEN: mOctBDVh8F8XeMQjFQQ3FUBdrxAifYjkbkUwDamD7lhDRvXXnp
    volumes:
      - ".:/project"
    networks:
      - hznet

  event_generator:
    image: openjdk:11
    command: java -jar /project/event-generator/target/event-generator-1.0-SNAPSHOT.jar
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev 
      MACHINE_COUNT: 2000
      VIRIDIAN_SECRETS_DIR: /project/hzcloud_c8930fck_keys
      VIRIDIAN_CLUSTER_ID: pr-c8930fck
      VIRIDIAN_PASSWORD: d2d46ffa1a2
      VIRIDIAN_DISCOVERY_TOKEN: mOctBDVh8F8XeMQjFQQ3FUBdrxAifYjkbkUwDamD7lhDRvXXnp
    volumes:
      - ".:/project"
    networks:
      - hznet
  
  ui:
    build:
      context: ./ui
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev
    ports:
      - "8050:8050"
    networks:
      - hznet
    profiles:
      - disabled


networks:
  hznet: 
  