services:

  submit_job:
    image: hazelcast/hazelcast-enterprise:5.2.1
    environment:
      CLASSPATH: /project/common/target/common-1.0-SNAPSHOT.jar
      VIRIDIAN_SECRETS_DIR: /project/hzcloud_q5je2628_keys
      VIRIDIAN_CLUSTER_ID: pr-q5je2628
      VIRIDIAN_PASSWORD: a78de577fb3
      VIRIDIAN_DISCOVERY_TOKEN: CDYb5U7ViM5qApsX9RrZLoJXuuBZJ12gE5IyrfLWFCXb1S3pN3
      MACHINE_COUNT: 10
      SIMULATOR_CONFIG_FILE: /project/config/machine_profiles_small.csv
    volumes:
      - ".:/project"
    command: /project/cli/viridian_submitjob.sh
    networks:
    - hznet
    profiles:
      - disabled

  cancel_job:
    image: hazelcast/hazelcast-enterprise:5.2.1
    environment:
      CLASSPATH: /project/common/target/common-1.0-SNAPSHOT.jar
      VIRIDIAN_SECRETS_DIR: /project/hzcloud_q5je2628_keys
      VIRIDIAN_CLUSTER_ID: pr-q5je2628
      VIRIDIAN_PASSWORD: a78de577fb3
      VIRIDIAN_DISCOVERY_TOKEN: CDYb5U7ViM5qApsX9RrZLoJXuuBZJ12gE5IyrfLWFCXb1S3pN3
    volumes:
      - ".:/project"
    command: /project/cli/viridian_canceljob.sh
    networks:
      - hznet
    profiles:
      - disabled

  refdata_loader:
    image: openjdk:11
    command: java -jar /project/refdata-loader/target/refdata-loader-1.0-SNAPSHOT.jar
    environment:
      VIRIDIAN_SECRETS_DIR: /project/hzcloud_q5je2628_keys
      VIRIDIAN_CLUSTER_ID: pr-q5je2628
      VIRIDIAN_PASSWORD: a78de577fb3
      VIRIDIAN_DISCOVERY_TOKEN: CDYb5U7ViM5qApsX9RrZLoJXuuBZJ12gE5IyrfLWFCXb1S3pN3
      MACHINE_COUNT: 10
      SIMULATOR_CONFIG_FILE: /project/config/machine_profiles_small.csv
    volumes:
      - ".:/project"
    networks:
      - hznet

  event_generator:
    image: openjdk:11
    command: java -jar /project/event-generator/target/event-generator-1.0-SNAPSHOT.jar
    environment:
      VIRIDIAN_SECRETS_DIR: /project/hzcloud_q5je2628_keys
      VIRIDIAN_CLUSTER_ID: pr-q5je2628
      VIRIDIAN_PASSWORD: a78de577fb3
      VIRIDIAN_DISCOVERY_TOKEN: CDYb5U7ViM5qApsX9RrZLoJXuuBZJ12gE5IyrfLWFCXb1S3pN3
      MACHINE_COUNT: 10
    volumes:
      - ".:/project"
    networks:
      - hznet
  
  ui:
    build:
      context: ./ui
    environment:
      VIRIDIAN_SECRETS_DIR: /project/hzcloud_q5je2628_keys
      VIRIDIAN_CLUSTER_ID: pr-q5je2628
      VIRIDIAN_PASSWORD: a78de577fb3
      VIRIDIAN_DISCOVERY_TOKEN: CDYb5U7ViM5qApsX9RrZLoJXuuBZJ12gE5IyrfLWFCXb1S3pN3
    ports:
      - "8050:8050"
    volumes:
      - ".:/project"
    networks:
      - hznet

networks:
  hznet: 
  